// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2aA4YhB0RokQqKbs8ZQ5rcSVqqdAlhLo',
    appId: '1:244607705559:web:b195737594207af29feb92',
    messagingSenderId: '244607705559',
    projectId: 'finance-ef741',
    authDomain: 'finance-ef741.firebaseapp.com',
    storageBucket: 'finance-ef741.appspot.com',
    measurementId: 'G-3G9KT4Z1XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCefqqinxW5r8SiDmCV6AsP4sAzsHvTnqc',
    appId: '1:244607705559:android:105ea4c8644d3b509feb92',
    messagingSenderId: '244607705559',
    projectId: 'finance-ef741',
    storageBucket: 'finance-ef741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-Hy7amqBjTlnyQwrv_7ID7ix7IEf9eU',
    appId: '1:244607705559:ios:f2c56790befcb83a9feb92',
    messagingSenderId: '244607705559',
    projectId: 'finance-ef741',
    storageBucket: 'finance-ef741.appspot.com',
    iosClientId: '244607705559-ca4rvr3njnh16hfeo6levmhbbkj7ncrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2-Hy7amqBjTlnyQwrv_7ID7ix7IEf9eU',
    appId: '1:244607705559:ios:f2c56790befcb83a9feb92',
    messagingSenderId: '244607705559',
    projectId: 'finance-ef741',
    storageBucket: 'finance-ef741.appspot.com',
    iosClientId: '244607705559-ca4rvr3njnh16hfeo6levmhbbkj7ncrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinance',
  );
}
